import React, { useState } from "react";
import Backdrop from "@mui/material/Backdrop";
import CircularProgress from "@mui/material/CircularProgress";
import LoaderComponent from "./Loader";
import DashboardCard01 from "../partials/dashboard/DashboardCard01";
import DashboardCard02 from "../partials/dashboard/DashboardCard02";
import DashboardCard03 from "../partials/dashboard/DashboardCard03";
import DashboardCard04 from "../partials/dashboard/DashboardCard04";
import DashboardCard05 from "../partials/dashboard/DashboardCard05";
import DashboardCard06 from "../partials/dashboard/DashboardCard06";
import DashboardCard07 from "../partials/dashboard/DashboardCard07";
import DashboardCard08 from "../partials/dashboard/DashboardCard08";
import DashboardCard09 from "../partials/dashboard/DashboardCard09";
import DashboardCard10 from "../partials/dashboard/DashboardCard10";
import DashboardCard11 from "../partials/dashboard/DashboardCard11";
import DashboardCard12 from "../partials/dashboard/DashboardCard12";
import DashboardCard13 from "../partials/dashboard/DashboardCard13";
import DashboardCard14 from "../partials/dashboard/DashboardCard14";
import DashboardCard15 from "../partials/dashboard/DashboardCard15";
import DashboardCard16 from "../partials/dashboard/DashboardCard16";
import axios from "axios";

const DataChat = () => {
  const [fileInput2, setFileInput2] = useState("");
  const [isDataFetched, setIsDataFetched] = useState(true);
  const [promptResult, setPromptResult] = useState(<></>);
  const [prompt, setPrompt] = useState("");

  const handleFileInput2 = (e) => {
    console.log(e.target.files[0]);
    setFileInput2(e.target.files[0]);
  };

  const promptMap = {
    "Compare the sales of the cities Pune, Mumbai, Chennai with a line graph": (
      <DashboardCard08 />
    ),
    "What is the average sales of Pune stores in 2024": <DashboardCard14 />,
    "Compare the revenue generated by Market Yard Store vs Viman Nagar Store": (
      <DashboardCard06 />
    ),
    "Display the popularity trends of products in different seasons": (
      <DashboardCard06 />
    ),
    "What is the average sales for the month of March?": <DashboardCard14 />,
  };

  console.log(fileInput2);
  console.log(Boolean(fileInput2));

  const handleSubmit = () => {
    setIsDataFetched(false);
    // formdata
    const formData = new FormData();
    fileInput2 && formData.append("code", fileInput2);
    formData.append("prompt", prompt);
    axios
      .post("http://localhost:5000/chat", formData, {
        headers: {
          "Content-Type": fileInput2
            ? "multipart/form-data"
            : "application/json",
        },
      })
      .then((res) => {
        console.log(res);
        const output = res.data || {};
        console.log({output});
        

        if (output.response_type === "Plot") {
          setPromptResult(
            <img
              src={`data:image/png;base64,${output.latest_image_url}`}
              alt="plot"
              style={{ width: "100%", height: "100%" }}
            />
          );
        } else if (
          output.response_type === "Number" ||
          output.response_type === "String" ||
          output.response_type === "DataFrame"
        ) {
          setPromptResult(<p>{output.response}</p>);
        }
        setIsDataFetched(true);
      })
      .catch((err) => {
        console.log(err);
        setIsDataFetched(true);
      });
  };

  console.log({promptResult});
  

  return (
    <div className="flex flex-col items-center h-screen">
      <div
        className="bg-white p-7 rounded mx-auto"
        style={{ display: "flex", alignItems: "center" }}
      >
        <div className="flex flex-col items-center justify-center py-10 text-center">
          {/* input csv file */}
          <div className="bg-white p7 rounded mx-auto">
            <div
              x-data="dataFileDnD()"
              className="relative flex flex-col p-4 text-gray-400 border border-gray-200 rounded"
            >
              {fileInput2 ? (
                <>{fileInput2?.name} Uploaded successfully</>
              ) : (
                <div
                  x-ref="dnd"
                  className="relative flex flex-col text-gray-400 border-dashed rounded cursor-pointer"
                >
                  <input
                    accept="*"
                    type="file"
                    multiple
                    className="absolute inset-0 z-50 w-full h-full p-0 m-0 outline-none opacity-0 cursor-pointer"
                    title=""
                    onChange={handleFileInput2}
                  />

                  <div className="flex flex-col items-center justify-center py-10 text-center">
                    <svg
                      className="w-6 h-6 mr-1 text-current-50"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
                      />
                    </svg>
                    <p className="m-0">
                      Drag your files here or click in this area.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
          <p className="m-0 mt-10">Enter the prompt and click on submit</p>
          <textarea
            type="text"
            className="border border-gray-200 rounded p-2"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            style={{ marginTop: "20px" }}
            rows="4"
          />
          <button
            className="btn bg-gray-900 text-gray-100 hover:bg-gray-800 dark:bg-gray-100 dark:text-gray-800 dark:hover:bg-white"
            style={{ marginTop: "20px" }}
            onClick={handleSubmit}
          >
            {" "}
            Submit{" "}
          </button>
        </div>
        <div>{promptResult}</div>
      </div>
    </div>
  );
};

export default DataChat;
